[package]
name = "ds210project"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
petgraph = "0.6"
assert_approx_eq = "1.1"
rand = "0.8"  

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }